name: 发送 Telegram 通知 (测试)

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit (sha 或描述)"
        required: true
        type: string
      change_log:
        description: "Change log"
        required: true
        type: string

permissions:
  contents: write

jobs:
  notify:
    name: 发送 Telegram 通知
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID_2 }}
      message_thread_id: ${secrets.message_thread_id}
    steps:
      - name: Send Telegram message
        shell: bash
        run: |
          set -euo pipefail

          NEW_TAG="${GITHUB_REF_NAME}"
          INPUT_COMMIT="${{ github.event.inputs.commit }}"
          INPUT_CHANGE_LOG="${{ github.event.inputs.change_log }}"

          TEXT=$(cat <<EOF
          <b>New Release Pushed:</b>
          
          Branch: <code>main</code>
          Commit: ${INPUT_COMMIT}
          Tag: <code>${NEW_TAG}</code>
          
          Features: 
          <pre>ReSukiSU = true
          SuSFS = true
          BBG = false
          LZ4KD = false
          Built-in KPM = false
          KPatch-Next Support =true</pre>
          Change Log: 
          <pre>${INPUT_CHANGE_LOG}
          </pre>
          Download: <a href="https://github.com/coolzyd9107/GKI_KernelSU_SUSFS/releases/tag/${NEW_TAG}">Click Here</a>

          Note: The "commit" here refers to ReSukiSU's commit, not this repository's.
          EOF
          )

          curl -s "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d message_thread_id="${message_thread_id}" \
            -d parse_mode="HTML" \
            --data-urlencode text="${TEXT}"
