name: Android 14 (6.1.172)

# Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      # KernelSU ReSukiSU
      kernelsu_branch:
        description: "KSU (main/dev/commit hash)"
        required: false
        type: string
        default: "main"
      version:
        description: "Custom version name"
        required: false
        type: string
      build_time:
        description: "Custom Build Time (blank = current UTC time)"
        required: false
        type: string
        default: "Sun Mar 22 08:10:00 UTC 2026"
      use_zram:
        description: "Enable ZRAM"
        required: true
        type: boolean
        default: false
      use_bbg:
        description: "Enable BBG"
        required: true
        type: boolean
        default: true
      use_rekernel:
        description: "Enable Re-Kernel"
        required: false
        type: boolean
        default: false
      enable_susfs:
        description: "Enable SUSFS"
        required: true
        type: boolean
        default: false
      enable_nomount:
        description: "Enable NoMount"
        required: true
        type: boolean
        default: true
      droidspaces:
        description: "Enable Droidspaces"
        required: false
        type: choice
        options:
          - "off"
          - "678"
          - "123"
          - "345"
        default: "off"
      droidspaces_ntsync:
        description: "Enable NTSync"
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      # KernelSU ReSukiSU
      kernelsu_branch:
        required: true
        type: string
      version:
        required: false
        type: string
      build_time:
        required: false
        type: string
        default: "Sun Mar 22 08:10:00 UTC 2026"
      use_zram:
        required: true
        type: boolean
      use_bbg:
        required: true
        type: boolean
      use_rekernel:
        required: false
        type: boolean
        default: false
      enable_susfs:
        required: false
        type: boolean
      enable_nomount:
        required: false
        type: boolean
      droidspaces:
        required: false
        type: string
        default: "off"
      droidspaces_ntsync:
        required: false
        type: boolean
        default: false
      called_from_main:
        description: "main.yml"
        required: false
        type: boolean
        default: false

jobs:
  build-kernels-a14-6-1:
    name: "6.1.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "172"
            os_patch_level: "2026-06"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_variant: "ReSukiSU"
      ksu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version || '' }}
      build_time: ${{ inputs.build_time || '' }}
      use_zram: ${{ inputs.use_zram }}
      use_bbg: ${{ inputs.use_bbg }}
      use_rekernel: ${{ inputs.use_rekernel || false }}
      supp_op: false
      enable_susfs: ${{ inputs.enable_susfs || false }}
      enable_nomount: ${{ inputs.enable_nomount  || false}}
      droidspaces: ${{ inputs.droidspaces || 'off' }}
      droidspaces_ntsync: ${{ inputs.droidspaces_ntsync || false }}

  # main.yml
  get-ksu-manager:
    if: ${{ !inputs.called_from_main }}
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
